---
title: "Data Import"
output: github_document
---
```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Data Import: CSVs

Let's import data using the `readr` package.

```{r}
litters_df = read_csv("data/data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
#package::function lets you use a function from a package
#janitor::clean_names cleans variable names, convert column names to lower snake case
```

#Looking at data
```{r}
litters_df #show whole df
tail(litters_df, 5) #show last 5 rows
skimr::skim(litters_df)
```

#Other file types

We need to read in an excel spreadsheet..

```{r}
mlb_df = read_excel("data/data_import_examples/mlb11.xlsx")
head(mlb_df, 5)
```

```{r}
lotR_words_df = read_excel(
  "data/data_import_examples/LotR_Words.xlsx", 
  range = "B3:D6" #only read part of the file
  )
```
## Still more formats

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/data_import_examples/public_pulse_data.sas7bdat")
```

## Data export

```{r}
write_csv(lotR_words_df, file = "data/lotR_words_df.csv")
```

## Why not base r?

```{r}
dont_do_this_df = read.csv("data/data_import_examples/FAS_litters.csv")
#don't do it! Use read_csv instead
```

